name: InfoUI
main: InfoUI\InfoUI
version: 1.0.0
api: 3.0.0, 4.0.0
description: A advanced plugin that allows you to see info about your PocketMine-MP server in an UI
commands:
    info:
        default: true
        description: Opens Information Menu!
